name: Sync repository info from package.json

env:
  GITHUB_TOKEN: ${{ secrets.UPDATE_REPO_INFO_PAT }}

permissions:
  contents: write

on:
  push:
    branches:
      - saga
    paths:
      - "package.json"
      - ".github/workflows/update-repo-info.yaml"
  workflow_dispatch:

jobs:
  update_repo_info:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Sync repository description
        run:
          gh repo edit --description "`cat package.json | jq -r '.description'`"

      - name: Sync repository topics
        run:
          cat package.json | jq '.keywords[]' | xargs -I'{}' gh repo edit
          --add-topic {}

      - name: Sync homepage
        run: gh repo edit --homepage "`cat package.json | jq -r '.homepage'`"
